use_frameworks!

target 'DoupQueue_Example' do
  pod 'DoupQueue', :path => '../'
  
  source 'https://github.com/CocoaPods/Specs.git'
  platform :ios, '8.0'
  use_frameworks!
  
  #pod 'XCGLogger', '~> 3.3'
  pod 'XCGLogger', :git => "https://github.com/DaveWoodCom/XCGLogger", :tag => "Version_3.3"
  #pod 'Alamofire', '~> 3.4'
  pod 'Alamofire', :git => "https://github.com/Alamofire/Alamofire", :tag => "3.4.0"
  
  target 'DoupQueue_Tests' do
    inherit! :search_paths
    pod 'Alamofire', :git => "https://github.com/Alamofire/Alamofire", :tag => "3.4.0"
    #pod 'Quick', '~> 0.8'
    pod 'Quick', :git => "https://github.com/Quick/Quick", :tag => "v0.8.0"
    #pod 'Nimble', '~> 3.0'
    pod 'Nimble', :git => "https://github.com/Quick/Nimble", :tag => "v3.0.0"
    #pod 'Nimble-Snapshots'
    #FYI :: Nimble & Nimble-Snapshots internally add FBSnapshotTestCase
  end
end

