# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage


language: objective-c
osx_image: xcode7.3
podfile: Example/Podfile
env:
   global:
   - LANG=en_US.UTF-8
   - WORKSPACE="Example/DoupQueue.xcworkspace"
   - IOS_SCHEME="DoupQueue"
   - IOS_SDK=iphonesimulator9.3

   matrix:
   - DESTINATION="OS=9.3,name=iPhone 6 Plus" SDK="$IOS_SDK" SCHEME="$IOS_SCHEME"
before_install:
 - rvm install ruby-2.2.2
 - gem install bundler
 - gem install cocoapods # Since Travis is not always on latest version
 - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
 - gem install xcpretty-travis-formatter --no-rdoc --no-ri --no-document --quiet
 - pod install --project-directory=Example

script:
 - pod lib lint --quick
 - set -o pipefail && xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO | xcpretty -f `xcpretty-travis-formatter` -c;
