# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
 - rvm install ruby-2.2.2
 - gem install cocoapods # Since Travis is not always on latest version
 - pod install --project-directory=Example
script:
#- set -o pipefail && xcodebuild test -workspace Example/DoupQueue.xcworkspace -scheme DoupQueue-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- set -e && xcodebuild -workspace Example/DoupQueue.xcworkspace -scheme DoupQueue-Example -sdk iphonesimulator test #| xcpretty -c
- pod lib lint
